### ISSUE TITLE
question

### ISSUE THREAD

**Issue by milkdrop2077** [iaddis/milkdrop2020#1]
hey, whats your program doing exactly? is it like beatdrop? is it an exe file? could you build a version? (I don't code in C++). thanks

**Comment by iaddis** [comment]
This is a port of the open sourced milkdrop2, more info can be found here:
[http://www.geisswerks.com/about_milkdrop.html](http://www.geisswerks.com/about_milkdrop.html)

**Comment by milkdrop2077** [comment]
thanks but I know exactly what milkdrop is, but I don't understand what milkdrop2020 does, and if I don't, not many people will!
how portable milkdrop2020 is? your description is too vague. does it need winamp to run? please build your Win32 version
